### ISSUE TITLE
Cannot parse more than one file with the same parser

### ISSUE THREAD

**Issue by themasch** [metroplex-systems/edifact#14]
We encountered an issue in our tests with the new version 3.1, introduced with this commit 7ea8b89c85405d725e093068e3f00f972b2495c9, which refactored the tokenizer & parser. 

The parser not does not create a new Tokenizer for every parse, but re-uses the same tokenizer. This tokenizers internally keeps its current read `$position` which does not get reset after parsing a file. Therefor the same parser can no longer be used to parse multiple documents. 

I'm just interested in if this is an intented design decision, or if we could get either a way to manually `reset` the tokenizer from the outside, or automatically reset it at the end of `Parser::parse`?

**Comment by duncan3dc** [comment]
Hi @themasch this is not intended at all, definitely a bug, let me look into it now for you...

**Comment by duncan3dc** [comment]
A fix for this is available in [3.1.1](https://github.com/estratocloud/edifact/releases/tag/3.1.1)

Sorry about that! I try to avoid state as much as possible, but unfortunately I've let some creep in here :man_facepalming: 

Happy coding!

**Comment by themasch** [comment]
Hey @duncan3dc, thanks for the fast response and fix! 
Now I can push the update including our workaround *AND* the removal of said workaround in the same PR ;) 

I updated and tested, works fine!
