### ISSUE TITLE
translatable into python

### ISSUE THREAD

**Issue by nerdoc** [metroplex-systems/edifact#2]
Hi Duncan,
I can't find another way to contact you, so I'll write an issue here. I found your library here, and kind of like it. Could you just tell me the status of the library, is it more-or-less tested for general use?

What I want is translate it into Python, as I have a bigger Python project in mind, and am in need of a EDIFACT library, which does not really exist within the Python world.

Do you think that your edifact libary is in a state that could be ported to python? Do you use it in a real-world project? Or was it abandonned 2 years ago?

Thanks,
Christian

**Comment by duncan3dc** [comment]
Hi Christian,

I use the library at my place of work in production, so it has proven stable.

We'll be pushing some of our work upstream here soon, so the project is not dead.

Thanks for your interest!

**Comment by nerdoc** [comment]
Cool, thanks! I think the code is very readable and looks quite clean.

**Comment by duncan3dc** [comment]
Thanks man, happy coding!

**Comment by nerdoc** [comment]
I'd like to use the (A)GPL3 for the (python) code - is that ok - edifact(PHP) is under the Apache 2.0 license, which "should" be compatible with the GPL3, at least in that direction. Any problems here?

**Comment by duncan3dc** [comment]
I'm not sure sorry, I won't come after you though 😃

**Comment by nerdoc** [comment]
FYI: started at https://github.com/nerdocs/pydifact. If I find a substantial flaw I'll try to re-translate it to your project ;-)
And If you are not comfortable with the GPL3 I chose there, please let me know.
Thanks
