### ISSUE TITLE
Repeating segments

### ISSUE THREAD

**Issue by davidvandertuijn** [metroplex-systems/edifact#6]
I'm trying to fetch repeating EQD segments from a EDIFACT BICS IFTMIN document however, it seems this library does not support this.

```
foreach ($oMessage->getSegments('EQD') as $oSegmentEqd) {
    $oSegmentMea = $oSegmentEqd->getSegment('MEA');
}
```

![bics_iftmin](https://user-images.githubusercontent.com/11010507/42825227-d90ff2b0-89e1-11e8-9f8c-41de812db826.png)

**Comment by duncan3dc** [comment]
Hi @davidvandertuijn, can you elaborate on how it doesn't support it?
Are you getting some kind of error? Or does `getSegments()` return an empty iterator?

Also can you provide a sample file to reproduce the issue with?

**Comment by davidvandertuijn** [comment]
Hi @duncan3dc thanks for your fast reply. This error occurs:

```Call to undefined method Metroplex\Edifact\Segments\Segment::getSegment()```

**Comment by duncan3dc** [comment]
Ah ok, so although that diagram represents it as a "nested" structure, EDIFACT doesn't actually support nesting, it just lists elements one after another.

You'd need to loop around all the elements, taking note of when the `EQD` segment appears, and then the segments that follow it.

Something a bit like this:
```php
$items = [];
$key = -1;
foreach ($oMessage->getAllSegments() as $oSegment) {
    $code = $oSegment->getSegmentCode();

    if ($code === 'EQD') {
        ++$key;
    }

    if (in_array($code, ['MEA', 'SEL', 'RFF'], true)) {
        $items[$key][$code] = $oSegment;
    }
}

foreach ($items as $children) {
    $oSegmentMea = $children['MEA'];
}
```

Hope this helps!

**Comment by davidvandertuijn** [comment]
Quick work-arround however, i'm worried what will happen if a segment exists with the same name outside the EQD block, for example UNB -> UNH -> GR18 -> GID -> GR29 -> SGP -> MEA. that MEA overwrite to the previous EQD block.

**Comment by duncan3dc** [comment]
You could add some more protection to the code above, but without specific end segments for the EQD section (which I don't think you have?) it's not going to be that reliable.

It's unfortunate the EDIFACT doesn't support nesting segments like XML and other serialization formats
