### ISSUE TITLE
serialize() changes the UNA segment

### ISSUE THREAD

**Issue by nerdoc** [metroplex-systems/edifact#7]
As you have more or less the same code, it will affect you too.
If using a custom UNA segment with non-standard characters, create a simple message and serialize it again, Serializer.serialize() will just create a standard UNA header and overwrite it.
See my bug: https://github.com/nerdocs/pydifact/issues/11

I added a check - please have a look at my python code - you unconditionally add the UNA header when serializing - which is bad when a custom character set is used.

**Comment by duncan3dc** [comment]
Hi @nerdoc, great to hear from you! I've been following your project and the vibrant community you've created :slightly_smiling_face: 

The way I handle a custom UNA segment is by passing a `ControlCharacters` instance to the serializer (https://github.com/estratocloud/edifact/commit/f8f6a80b247430e7ed06c730e7517c951debcffa) so my library doesn't support manually creating a `UNA`

**Comment by nerdoc** [comment]
Ok! thanks!
